name: Backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        cd backend
        pip install -r requirements.txt requirements_tests.txt

    - name: Run Tests
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: |
        cd backend
        pytest .
